name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: php-actions/composer@dynamic-docker

      - name: PHPUnit Tests
        uses: php-actions/phpunit@dynamic-docker
        with:
          configuration: tests/phpunit.xml
          args: --coverage-text
          
      - name: PHPStan Static Analysis
        uses: php-actions/phpstan@v2
        with:
          configuration: phpstan.neon.dist
          memory_limit: 256M