name: PHP CI
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v1
      - uses: php-actions/phpstan@v2
        with:
          configuration: phpstan.neon.dist
  
  tests:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v1
      - name: PHPUnit Tests
        uses: php-actions/phpunit@v9
        with:
          configuration: tests/phpunit.xml
          args: --coverage-text

  deploy_dev:
#     needs: [lint, tests]
#     if: github.ref == 'refs/heads/deploy_dev'
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v2
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      - run: mkdir ~/.ssh; chmod 711 ~/.ssh
      - run: echo "${{Secrets.PRIVATE_KEY}}" >> ~/.ssh/id_rsa
      - run: cd ~/.ssh && ls -a
      - run: ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run: ssh-agent --a $SSH_AUTH_SOCK > /dev/null
      - run: ssh-add - <<< "${{ Secrets.PRIVATE_KEY }}"
      - run: git clone git@bitbucket.org:redmal/securconfig.git
           
  deploy_prod:
    needs: [lint, tests]
    if: github.ref == 'refs/heads/deploy_prod'
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v2
      - run: ls
