name: PHP CI
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v1
      - uses: php-actions/phpstan@v2
        with:
          configuration: phpstan.neon.dist
  
  tests:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v1
      - name: PHPUnit Tests
        uses: php-actions/phpunit@v9
        with:
          configuration: tests/phpunit.xml
          args: --coverage-text

  deploy_dev:
#     needs: [lint, tests]
#     if: github.ref == 'refs/heads/deploy_dev'
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v2
      - run: git clone https://${{Secrets.BITBUCKET_LOGIN}}:${{Secrets.BITBUCKET_PASSWORD}}@bitbucket.org/litesoftteam/securconfig.git
      - run: cp securconfig/db_params.php app/core/config/
      - run: ls
#       - run: mkdir ~/.ssh; chmod 711 ~/.ssh
#       - run: echo "${{Secrets.PRIVATE_KEY}}" >> ~/.ssh/id_rsa
#       - run: cd ~/.ssh && ls -a
#       - run: ssh-keyscan github.com >> ~/.ssh/known_hosts
#       - run: eval 'ssh-agent -s'
#       - run: sudo ssh-agent
#       - run: git config --list
#       - run: ssh-add -l
#       - run: ssh-agent --a $SSH_AUTH_SOCK > /dev/null
#       - run: ssh-add ~/.ssh/id_rsa
#       - run: git clone git@bitbucket.org:redmal/securconfig.git
