name: PHP CI
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v1
      - uses: php-actions/phpstan@v2
        with:
          configuration: phpstan.neon.dist
  
  tests:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v1
      - name: PHPUnit Tests
        uses: php-actions/phpunit@v9
        with:
          configuration: tests/phpunit.xml
          args: --coverage-text

  deploy_dev:
#     needs: [lint, tests]
#     if: github.ref == 'refs/heads/deploy_dev'
    runs-on: ubuntu-latest    
    env:
      REPO_NAME: ${{ github.event.repository.name }}
    steps:
      - uses: actions/checkout@v2
      - run: git clone https://${{Secrets.BITBUCKET_LOGIN}}:${{Secrets.BITBUCKET_PASSWORD}}@bitbucket.org/litesoftteam/securconfig.git
      - run: cp securconfig/db_params.php app/core/config/
      - run: rm -R securconfig
      - run: echo $HOME
      - run: echo ~
      - run: echo $PWD
      - run: ls
      - run: ls app/core/config/
      
#       - name: Dump github context
#         run:   echo "$GITHUB_CONTEXT"
#         shell: bash
#         env:
#           GITHUB_CONTEXT: ${{ toJson(github) }}
      
      - run: echo $REPO_NAME

#     - run: ssh gvozde0m_develop@gvozde0m.beget.tech "ls"
      
      - run: sshpass -p "${{Secrets.BEGET_PASSWORD}}" ssh -t -o StrictHostKeyChecking=no gvozde0m_develop@gvozde0m.beget.tech "ls"
      - run: sshpass -p "${{Secrets.BEGET_PASSWORD}}" ssh -t -o StrictHostKeyChecking=no gvozde0m_develop@gvozde0m.beget.tech "rm -R $REPO_NAME"
      - run: sshpass -p "${{Secrets.BEGET_PASSWORD}}" ssh -t -o StrictHostKeyChecking=no gvozde0m_develop@gvozde0m.beget.tech "ls"
      
      - run: sshpass -p "${{Secrets.BEGET_PASSWORD}}" rsync -av -e ssh --exclude '.gitignore' --exclude '.git' --exclude 'composer.lock' $PWD gvozde0m_develop@gvozde0m.beget.tech:~/$REPO_NAME
        
#       - run: mkdir ~/.ssh; chmod 711 ~/.ssh
#       - run: echo "${{Secrets.PRIVATE_KEY}}" >> ~/.ssh/id_rsa
#       - run: cd ~/.ssh && ls -a
#       - run: ssh-keyscan github.com >> ~/.ssh/known_hosts
#       - run: eval 'ssh-agent -s'
#       - run: sudo ssh-agent
#       - run: git config --list
#       - run: ssh-add -l
#       - run: ssh-agent --a $SSH_AUTH_SOCK > /dev/null
#       - run: ssh-add ~/.ssh/id_rsa
#       - run: git clone git@bitbucket.org:redmal/securconfig.git
